name: Mit dem Fahrrad nach Venezuela
favicon: null
layout_spectrum: 0.3026464644353837
typography_spectrum: 0.2966695490758866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9777306641917676
  lightness: 0.9998924941755831
  saturation: 0.04200990917161107
  rhythmicContrast: 0.8808687014970928
purpose: []
